add_newline = true
command_timeout = 1000

format = "$directory$git_branch$git_status$nodejs$python$cmd_duration\n$character\n"

[directory]
truncation_length = 3
truncate_to_repo = true
style = "bold white"
read_only = " 󰌾"
read_only_style = "red"

[git_branch]
symbol = " "
format = "[$symbol$branch]($style) "
style = "purple"

[git_status]
format = '([$ahead_behind$staged$modified$untracked$conflicted]($style) )'
style = "bold cyan"
ahead = "↑$count"
behind = "↓$count"
diverged = "↑$ahead_count↓$behind_count"
staged = " +$count"
modified = " !$count"
untracked = " ?$count"
conflicted = " ~$count"

[nodejs]
format = "[·v$version]($style) "
style = "dimmed green"
detect_files = ["package.json", ".nvmrc"]
detect_folders = ["node_modules"]
disabled = false

[bun]
disabled = true

[python]
format = "[·$version]($style) "
style = "dimmed green"
detect_files = ["pyproject.toml", "requirements.txt", ".python-version", "uv.lock"]
detect_folders = [".venv", "venv"]
disabled = false

[cmd_duration]
min_time = 2000
format = "[·$duration]($style) "
style = "yellow"

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"
